chapter-10-scheduled-apex/main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <label>Log</label>
    <nameField>
        <displayFormat>L-{0000}</displayFormat>
        <label>Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

chapter-05-testing-apex/main/default/objects/Log__c/fields/Log_Message__c.field-meta.xml
<CustomField>
    <fullName>Log_Message__c</fullName>
    <label>Log Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

chapter-04-exception-handling/main/default/objects/Log__c/fields/Stack_Trace__c.field-meta.xml
<CustomField>
    <fullName>Stack_Trace__c</fullName>
    <label>Stack Trace</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

chapter-07-utilizing-future-methods/main/default/objects/Log__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Log</fullName>
            </value>
            <value>
                <fullName>Exception</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

chapter-04-exception-handling/main/default/classes/Logger.cls
public with sharing class Logger {
    
    private static List<Log__c> currentLogs;

    public static void addLog(String stackTrace, String logMessage, String logType) {
        if(currentLogs == null) {
            currentLogs = new List<Log__c>();
        }
        Log__c log = new Log__c();
        log.Stack_Trace__c = stackTrace;
        log.Log_Message__c = logMessage;
        log.Type__c = logType;
        currentLogs.add(log);
    }

    public static void persistLogs() {
        if(currentLogs != null && currentLogs.size() > 0) {
            insert currentLogs;
            currentLogs = new List<Log__c>();
        }
    }

    public static void logWithState(String stackTrace, String logMessage, String logType, Object instance) {
        Log__c log = new Log__c();
        log.Stack_Trace__c = stackTrace;
        log.Log_Message__c = logMessage;
        log.Type__c = logType;
        insert log;
        
        ContentVersion cv = new ContentVersion();
        cv.VersionData = Blob.valueOf(JSON.serializePretty(instance));
        cv.Title = 'Log of state at ' + Datetime.now();
        cv.PathOnClient = 'Log of state at ' + Datetime.now();
        insert cv;

        ContentDocumentLink cdl = new ContentDocumentLink();
        cdl.ContentDocumentId = [SELECT ContentDocumentId FROM ContentVersion WHERE Id = :cv.Id].ContentDocumentId;
        cdl.LinkedEntityId = log.Id;
        cdl.ShareType = 'V';

        insert cdl;
    }

    public static void log(String stackTrace, String logMessage, String logType) {
        Log__c log = new Log__c();
        log.Stack_Trace__c = stackTrace;
        log.Log_Message__c = logMessage;
        log.Type__c = logType;
        insert log;
    }

}