chapter-11-platform-events/main/default/objects/Demonstration__e/Demonstration__e.object-meta.xml
<CustomObject>
    <label>Demonstration</label>
    <pluralLabel>Demonstrations</pluralLabel>
</CustomObject>

chapter-11-platform-events/main/default/objects/Demonstration__e/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <label>Message</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DemonstrationEventPublisher.cls
public with sharing class DemonstrationEventPublisher {
    
    public static Boolean publishEventWithMessage(String message) {
        Demonstration__e demo = new Demonstration__e();
        demo.Message__c = message;
        Database.SaveResult result = Eventbus.publish(demo);
        System.debug('The publish event was a success: ' + result.isSuccess());
		return result.isSuccess();
    }

    // public static void publishEventsWithMessages(List<String> messages) {
    //     List<Demonstration__e> demos = new List<Demonstration__e>();
    //     for(String message : messages) {
    //         Demonstration__e demo = new Demonstration__e();
    //         demo.Message__c = message;
    //         demos.add(demo);
    //     }
    //     Database.SaveResult result = Eventbus.publish(demos);
    //     System.debug('The publish event was a success: ' + result.isSuccess());
    // }
}