chapter-07-utilizing-future-methods/main/default/objects/Future_Job__c/Future_Job__c.object-meta.xml
<CustomObject>
    <label>Future Job</label>
    <nameField>
        <displayFormat>FJ-{0000}</displayFormat>
        <label>Future Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Future Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

chapter-07-utilizing-future-methods/main/default/objects/Future_Job__c/fields/Data_for_Processing__c.field-meta.xml
<CustomField>
    <fullName>Data_for_Processing__c</fullName>
    <label>Data for Processing</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Future_Job__c/fields/Error_Information__c.field-meta.xml
<CustomField>
    <fullName>Error_Information__c</fullName>
    <label>Error Information</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

chapter-07-utilizing-future-methods/main/default/classes/CreateUser_Future.cls
public class CreateUser_Future {
	@future
	public static void createUser(Id futureJobId) {
		Future_Job__c job = [SELECT Data_for_Processing__c, Error_Information__c FROM Future_Job__c WHERE Id = :futureJobId];
		ContactWrapper wrapper = (ContactWrapper)(JSON.deserializeStrict(job.Data_for_Processing__c, ContactWrapper.class));
		try {
			insert wrapper.generateContact();
			delete job;
		} catch(Exception ex) {
			job.Error_Information__c = JSON.serializePretty(ex);
			update job;
		}
	}
}