force-app/main/default/objects/UpdateAccount__e/UpdateAccount__e.object-meta.xml
<CustomObject>
    <label>Update Account</label>
    <pluralLabel>Update Accounts</pluralLabel>
</CustomObject>

chapter-11-platform-events/main/default/objects/UpdateAccount__e/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <label>Account Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

chapter-11-platform-events/main/default/objects/UpdateAccount__e/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <label>Account Number</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

chapter-11-platform-events/main/default/classes/UpdateAccountEventTrigger_Test.cls
@isTest
private with sharing class UpdateAccountEventTrigger_Test {
    
    @isTest
    private static void testPublishAndRetry() {
        String accName = 'HM Bonding Ltd';

        Test.startTest();

        UpdateAccount__e evt = new UpdateAccount__e ();
        evt.Account_Name__c = accName;
        evt.Account_Number__c = '007';
        EventBus.publish(evt);

        Test.getEventBus().deliver();

        EventBusSubscriber[] subscribers = [SELECT Name, Type, Position, Retries, LastError FROM EventBusSubscriber WHERE Topic='UpdateAccount__e'];
            
        for (EventBusSubscriber sub : subscribers) {  
            if (sub.Name == 'UpdateAccountEventTrigger') {
                System.assertEquals(1, sub.Retries);
            } 
        }

        Account acc = new Account();
        acc.Name = accName;
        insert acc;

        Test.getEventBus().deliver();

        Test.stopTest();

        acc = [SELECT AccountNumber FROM Account WHERE Id = :acc.Id LIMIT 1];
        System.assertEquals('007', acc.AccountNumber, 'Incorrect Account Number set');
    }
}